# Generated by Django 4.1.2 on 2022-12-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='квартира')),
                ('utility_costs', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='коммуналка')),
                ('phone', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='телефон')),
                ('internet', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='интернет')),
                ('transport', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='транспорт')),
            ],
        ),
    ]
