# Generated by Django 4.1.2 on 2022-12-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='аванс')),
                ('date', models.DateField(auto_now=True, verbose_name='дата поступелния')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ЗП')),
                ('date', models.DateField(auto_now=True, verbose_name='дата поступелния')),
            ],
        ),
        migrations.AddField(
            model_name='expenses',
            name='per_day',
            field=models.DecimalField(decimal_places=2, default='20', max_digits=8, verbose_name='за день'),
            preserve_default=False,
        ),
    ]
