# Generated by Django 4.1.2 on 2022-12-17 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expences', '0003_salery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salery',
            new_name='Salary',
        ),
    ]
