# Generated by Django 4.1.2 on 2022-12-17 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expences', '0004_rename_salery_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeandexpediture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expences', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_salary', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
