# Generated by Django 4.1.2 on 2022-12-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0005_alter_incomeandexpediture_user_alter_salary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeandexpediture',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
