# Generated by Django 4.1.2 on 2022-12-17 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expences', '0006_incomeandexpediture_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Расход на день')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_per_day', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
