# Generated by Django 4.1.2 on 2022-12-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0008_alter_perday_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='status',
            field=models.BooleanField(default=True, verbose_name='статус'),
            preserve_default=False,
        ),
    ]
