# Generated by Django 4.1.2 on 2022-12-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0009_salary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='дата изменения'),
        ),
    ]
