# Generated by Django 4.1.2 on 2022-12-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0012_alter_reserv_user_alter_reserv_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Значение'),
        ),
    ]
