# Generated by Django 4.1.2 on 2022-12-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0013_alter_reserv_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='name',
            field=models.CharField(choices=[('зарплата', 'зарплата'), ('аванс', 'аванс')], default='аванс', max_length=50, verbose_name='Наименование'),
        ),
    ]
