# Generated by Django 4.1.2 on 2022-12-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0014_alter_salary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='name',
            field=models.CharField(choices=[('аванс', 'аванс'), ('зарплата', 'зарплата')], default='зарплата', max_length=50, verbose_name='Наименование'),
        ),
    ]
