# Generated by Django 4.1.2 on 2022-12-22 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expences', '0015_alter_salary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='name',
            field=models.CharField(choices=[('зарплата', 'зарплата'), ('аванс', 'аванс')], default='зарплата', max_length=50, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='AdditionalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значение')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_additional_income', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
