# Generated by Django 4.1.2 on 2023-01-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0016_alter_salary_name_additionalincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='perday',
            name='day',
            field=models.DateField(blank=True, null=True, verbose_name='День зарплаты'),
        ),
    ]
