# Generated by Django 4.1.2 on 2023-01-13 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0018_perday_salary_method_alter_salary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perday',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 1, 13, 22, 2, 33, 669864), verbose_name='День зарплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perday',
            name='salary_method',
            field=models.BooleanField(default=True, verbose_name='Расчет за полный месяц'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='name',
            field=models.CharField(choices=[('зарплата', 'зарплата'), ('аванс', 'аванс')], default='зарплата', max_length=50, verbose_name='Наименование'),
        ),
    ]
