# Generated by Django 4.1.2 on 2023-01-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expences", "0019_alter_perday_day_alter_perday_salary_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perday",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=100,
                verbose_name="Реальный баланс карты",
            ),
        ),
    ]
