# Generated by Django 4.1.2 on 2023-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0020_perday_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalincome',
            name='status',
            field=models.BooleanField(default=True, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='name',
            field=models.CharField(choices=[('аванс', 'аванс'), ('зарплата', 'зарплата')], default='зарплата', max_length=50, verbose_name='Наименование'),
        ),
    ]
