# Generated by Django 4.1.2 on 2023-02-11 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expences", "0021_additionalincome_status_alter_salary_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expediture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Наименование")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Значение"
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now=True, verbose_name="дата изменения"),
                ),
                ("status", models.BooleanField(verbose_name="Оплачено")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_expences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reserv",
            name="value_of_days_exp",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=100,
                verbose_name="Остаток на ежедневные расходы до конца месяца",
            ),
        ),
        migrations.AlterField(
            model_name="perday",
            name="salary_method",
            field=models.CharField(
                choices=[
                    ("Расчет за полный месяц", "Расчет за полный месяц"),
                    (
                        "Расчет по факту зачисления",
                        "Расчет по мере зачисления на карту",
                    ),
                ],
                default="Расчет за полный месяц",
                max_length=50,
                verbose_name="Способ расчета",
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="status",
            field=models.BooleanField(default=True, verbose_name="статус"),
        ),
        migrations.DeleteModel(
            name="IncomeAndExpediture",
        ),
    ]
