# Generated by Django 4.1.2 on 2023-02-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expences", "0025_remove_reserv_value_of_days_exp_alter_salary_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perday",
            name="salary_method",
            field=models.CharField(
                choices=[
                    (
                        "Расчет по факту зачисления",
                        "Расчет по мере зачисления на карту",
                    ),
                    ("Расчет за полный месяц", "Расчет за полный месяц"),
                ],
                default="Расчет за полный месяц",
                max_length=50,
                verbose_name="Способ расчета",
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="name",
            field=models.CharField(
                choices=[("зарплата", "зарплата"), ("аванс", "аванс")],
                default="зарплата",
                max_length=50,
                verbose_name="Наименование",
            ),
        ),
    ]
