# Generated by Django 4.1.2 on 2023-02-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expences", "0026_alter_perday_salary_method_alter_salary_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perday",
            name="salary_method",
            field=models.CharField(
                choices=[
                    ("Расчет за полный месяц", "Расчет за полный месяц"),
                    (
                        "Расчет по факту зачисления",
                        "Расчет по мере зачисления на карту",
                    ),
                ],
                default="Расчет за полный месяц",
                max_length=50,
                verbose_name="Способ расчета",
            ),
        ),
    ]
