# Generated by Django 4.1.2 on 2023-02-24 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sport", "0002_subscriptionvisit_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionvisit",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_subscription_visits",
                to="sport.subscriptionmodel",
                verbose_name="Абонемент",
            ),
        ),
    ]
